# Generated by Django 5.2.14 on 2026-05-26 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=50)),
                ('plant_name', models.CharField(max_length=255)),
                ('location', models.CharField(help_text='e.g., Frankfurt, Germany or New York, US', max_length=255)),
                ('grid_region', models.CharField(help_text='e.g., eGRID:NYUP, Grid:Germany, Grid:UK. Used to resolve Scope 2 grid emission factors.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP Fuel & Procurement'), ('UTILITY', 'Utility electricity bills'), ('TRAVEL', 'Corporate travel platform')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('SUCCESS', 'Successfully Processed'), ('FAILED', 'Failed Processing')], default='PENDING', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('total_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(help_text='Normalized activity occurrence date')),
                ('scope_type', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Direct Emissions'), ('SCOPE_2', 'Scope 2 - Indirect Energy Emissions'), ('SCOPE_3', 'Scope 3 - Other Indirect Emissions')], max_length=15)),
                ('category', models.CharField(help_text='e.g., Diesel, Electricity, Flights, Procurement, Hotels', max_length=50)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(help_text='Original unit: e.g., Liters, Gallons, MWh, Miles', max_length=50)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('normalized_unit', models.CharField(help_text='SI standardized unit: e.g., Liters, kWh, pkm', max_length=50)),
                ('emission_factor', models.DecimalField(decimal_places=6, help_text='tCO2e per normalized unit', max_digits=12)),
                ('co2e_emissions', models.DecimalField(decimal_places=6, help_text='Calculated total emissions in metric tons (tCO2e)', max_digits=18)),
                ('source_system', models.CharField(default='SAP', max_length=20)),
                ('plant_code', models.CharField(blank=True, help_text='Plant/facility code as ingested', max_length=50, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved (Locked)'), ('FLAGGED', 'Flagged (Suspicious)'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=15)),
                ('review_notes', models.TextField(blank=True, help_text='Auditor/Analyst review comments', null=True)),
                ('validation_warnings', models.JSONField(blank=True, default=list, help_text='List of triggers why record is flagged')),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='ingestion.facility')),
                ('ingestion_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_records', to='ingestion.ingestionjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.organization')),
            ],
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='ingestion.organization'),
        ),
        migrations.AddField(
            model_name='facility',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='ingestion.organization'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(help_text='Username of the analyst performing modification', max_length=100)),
                ('action', models.CharField(help_text='e.g. CREATE, UPDATE, APPROVE, REJECT', max_length=50)),
                ('previous_values', models.JSONField(help_text='Historical state snapshot')),
                ('new_values', models.JSONField(help_text='Updated state snapshot')),
                ('reason', models.TextField(help_text='Why the change was made - MANDATORY for edits')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.normalizedrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20)),
                ('raw_payload', models.JSONField(help_text='Original JSON representation of the row')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.organization')),
            ],
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='raw_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_record', to='ingestion.rawrecord'),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('organization', 'plant_code')},
        ),
    ]
